# Generated by Django 4.2.5 on 2023-10-09 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('fecha_creation', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizada', models.DateTimeField(null=True)),
                ('ingredientes', models.TextField(blank=True)),
                ('preparacion', models.TextField(blank=True)),
                ('email_p', models.EmailField(max_length=254)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
