# Generated by Django 4.2.5 on 2023-10-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_alter_publicaciones_contacto_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='contacto_tel',
            field=models.IntegerField(default=000000000),
        ),
    ]
