# Generated by Django 4.2.5 on 2023-10-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0004_alter_publicaciones_contacto_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='imagen_p',
            field=models.ImageField(default='default_image.jpg', upload_to='secun/images'),
        ),
    ]
