# Generated by Django 4.2.5 on 2023-10-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_publicaciones_imagen_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='imagen_redimensionada',
            field=models.ImageField(default='default_image.jpg', upload_to='redimens/images'),
        ),
    ]
