# Generated by Django 4.2.5 on 2023-10-13 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0008_personas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='user',
        ),
    ]
